### ISSUE TITLE
Warning, everything you type in the search bar will be sent to your Discourse instance.

### ISSUE THREAD

**Issue by sunjam** [nextcloud/integration_discourse#5]
Please clarify documentation for how Unified Search impacts the attached Discourse instance and any security concerns if a user enables search of posts and topics within their Nextcloud.

 `Warning, everything you type in the search bar will be sent to your Discourse instance.`

Thank you, and thanks for working on this integration.

**Comment by eneiluj** [comment]
The security warning is just mentioning that if you enable Discourse search, what you type in the search bar will naturally be sent to the Discourse instance (to search in it :grin:) even if you were just searching for a local file. Just a warning.

It does not affect the Discourse instance security.

**Comment by sunjam** [comment]
Thanks, I've filed a request to make it possible for users to interactively turn/off whether their unified search includes external services.
